#!/bin/bash

if ps -ef | grep node | grep -v grep | awk '{print $2}' | xargs kill -2
	then echo "Node stopped successfully"
fi
if ps -ef | grep mongod | grep -v grep | awk '{print $2}' | xargs kill -2
	then echo "Mongod stopped successfully"
fi

